owncloud/files_primary_s3

- .drone.yml
`owncloudci/core` - simplifies the boilerplate code for setting up testing of owncloud apps
Ref: https://github.com/owncloud-ci/core
> simplify drone yml by using owncloudci/core for server setup

- .drone.yml
https://github.com/owncloud/core/pull/30781 removes the necessity to rely on environment variables for testing objectstore - but resorts to using the configuration
> Sync test case changes with files_primary_s3

- .drone.yml
Run the "whole" API and webUI acceptance tests by specifying the tags of scenarios that we do not want to run:
``~@app-required`` - do not run scenarios that require some other app to be cloned/installed/enabled
``~@skip`` - do not run skipped scenarios (these are usually ones that demonstrate a bug waiting to be fixed
``~@masterkey_encryption`` - do not run scenarios that switch masterkey encryption (these do not work in the normal flow of API acceptance tests)
See also #78 for an alternate approach.
> Run acceptance tests without ones that require extra apps

- .drone.yml
- .gitignore
use the restored composer cache when installing core from a source branch
> use composer cache for core

- .drone.yml
as we have backported changes for objectstorage to stable10 - we should now also test it thorougly
Right now it's using php7.1 + php7.2 for unit tests - we need to clarify if we support php 5.6 / 7.0 or stick with 7.1
In this PR I have changed from testing acceptance on scality + ceph for testing only on ceph  - but this is also open for feedback / discussion. It seemed as if ceph would provide better performance in our scenarios
> test with stable10

- .drone.yml
For our QA/Engineering team to only monitor one channel for nightly build runs - a new notification section was added.
@DeepDiver1975 - please clarify if the objectstore team should still be notified separately or not
> build notifications

- .drone.yml
- .gitignore
- .php_cs.dist
Caching currently is not properly done for composer/npm - this PR should adress it and thus slice of a couple of minutes of built time
> proper caching for npm/composer

- .drone.yml
and use a proper separate federated server, like is done in core nowadays.
This is "a good thing" and also needed to make CI pass, because some core scenarios now create ``user1`` on both LOCAL and REMOTE servers and expect them to be 2 independent users. That passes only if the REMOTE federated server is truly a separate server.
Thanks to @individual-it for the code to do this in core, which I was able to easily steal and put here also. This is where "drone include files" would be useful, to suck in common snippets of ``drone.yml`` code that are the same in apps.
> Use core acceptance tests run.sh

- composer.lock
```
Updating dependencies (including require-dev)
Package operations: 0 installs, 9 updates, 0 removals
- Updating react/promise (v2.6.0 => v2.7.0): Loading from cache
- Updating guzzlehttp/ringphp (1.1.0 => 1.1.1): Loading from cache
- Updating guzzlehttp/guzzle (5.3.2 => 5.3.3): Loading from cache
- Updating aws/aws-sdk-php (3.62.2 => 3.64.10): Downloading (100%)         
- Updating symfony/polyfill-php72 (v1.8.0 => v1.9.0): Loading from cache
- Updating paragonie/random_compat (v2.0.15 => v9.99.99): Loading from cache
- Updating symfony/polyfill-php70 (v1.8.0 => v1.9.0): Loading from cache
- Updating symfony/polyfill-mbstring (v1.8.0 => v1.9.0): Loading from cache
- Updating friendsofphp/php-cs-fixer (v2.12.1 => …
```
> Version bumps for dependencies

- appinfo/info.xml
- lib/command/s3list.php
Refrences: https://github.com/owncloud/files_primary_s3/issues/111 (Rename occ command s3:ls to s3:list for better identification)
This PR does two things:
- renaming the file ``ls.php`` --> ``s3list.php``
- renaming the command from ``s3:ll`` --> ``s3:list``
Documentation relevant, will file a doc issue asap
> Rename command s3:ls to s3:list

- .drone.yml
As the official demo containers are dropped - we temporarily provide the container via `owncloudci/ceph:tag`
> Use ceph docker container from owncloudci organisation

- .drone.yml
The core ``tests/drone/test-acceptance.sh`` script no longer runs as ``www-data``.
So it has no priv to create the ``tests/acceptance/work/local_storage`` folder.
Create it earlier in the drone pipeline so it is available, the same as is done in core.
> Create local_storage folder when running API acceptance tests

- .drone.yml
because core ``run.sh`` does it via the testing app nowadays.
> Preconfigure local_storage is no longer needed in drone

- .drone.yml
introduce skip tags for different storages
e.g. `@skipOnStorage:ceph`
P.S. `@masterkey_encryption` seems not to be used anywhere, no idea why it was here, maybe copy paste error
> skip acceptance tests for specific storage

- tests/drone/ceph.config.php
- tests/drone/scality.config.php
Within `files_primary_S3` this option is no longer available. Remove the option from the test configuration as it implies it might still have an effect
> drop unavailable autocreate option

- .drone.yml
The drone ``api-acceptance-tests`` pipeline step was running an old ``tests/drone/test-acceptance.sh``
That did not process the splitting of test suites into parts, so all the API tests were running in the first part 1 of 5. Parts 2,3,4,5 were running nothing (and finishing in a few minutes).
Change the drone pipeline step to do similar to ``webui-acceptance-tests``
This reduces the elapsed time for running CI from 3 to 4 hours to about 1.5 hours.
I have checked the drone result, and all the core API suites are being run across the 5 "parts" of core API acceptance tests.
> Fix splitting core API tests into parts

- .drone.yml
- tests/drone/create-bucket.sh
Issue #170 
When the ``ceph`` docker starts up, it starts listening on its port. So
```
wait-for-it ceph:80
```
sees that ``ceph`` is up.
The ``ceph`` container also creates ``CEPH_DEMO_UID`` with ``CEPH_DEMO_ACCESS_KEY`` and ``CEPH_DEMO_SECRET_KEY`` but that takes a variable amount of time. So actually the ``CEPH_DEMO_UID`` might not be ready.
This new script ``create-bucket.sh`` loops trying to do the ``occ s3:create-bucket`` until it succeeds, or until it has tried 10 times at 10-second intervals. That should prevent intermittent fails when there is some ``ceph`` delay, but still give up and exit when something really is wrong.
> loop when creating bucket for testing

- Makefile
- vendor-bin/behat/composer.json
Like done in core PR https://github.com/owncloud/core/pull/34212
Note: this repo does not have any acceptance tests of its own. It only runs acceptance tests from core. But core QA tarball no longer has any pre-installed behat, so we need to set up the ``vendor-bin/behat`` stuff here.
> Install and run behat from vendor-bin

- lib/s3storage.php
Provide return status for writeObject method.
This would help to know if the upload to
object storage was successful or not.
Signed-off-by: Sujith H <sharidasan@owncloud.com>
> Always provide return status for functions

- .drone.yml
show only useful logs
the loglevel 0 does not help because most of the logs is cut away
This will also help to debug the current CI issues
> only show useful logs

- .drone.starlark
- .drone.yml
- Makefile
1) Run core acceptance tests in 25 parts (like is done in the encryption app, to reduce the total time of a single part)
2) Run core acceptance tests in a similar way to the encryption app, by having `Makefile` have the knowledge of how to do it, in targets like `test-acceptance-core-api`
3) Have the starlark code set `S3_TYPE` based on  cephS3 and scalityS3 settings (rather than having to set both of these in unison)
> Update drone starlark

- .drone.starlark
- .drone.yml
The drone agents are sometimes taking "a long time" (tm) to pull docker images. In particular this is a problem when it takes a long time to pull the database image (mariadb, postgresql, oracle...). The `install-core` step waits 120 seconds for the database to become available. If the pull took more than 2 minutes, then we get a timeout in `install-core` and the pipeline fails. That means the whole build fails and it has to be started all over again. That is very annoying.
This is seen mostly first thing in the morning, when the autoscaler starts new drone agents. Specially if a lot of drone agents get started at a similar time, they seem to be slow to pull each docker image the first time. After that, they have the docker images cached, so later pulls of the docker images do not have …
> Increase wait-for-db timeout from 120 to 600 seconds

- .drone.starlark
- .drone.yml
core PR https://github.com/owncloud/core/pull/36629 split acceptance tests into more suites. There are now 32 API suites and 27 webUI suites. We might as well run in this number of parts so that every suite runs in its own pipeline, optimizing the total elapsed run time.
> Increase numberOfParts in drone due to core 36629

- lib/command/createbucket.php
- lib/command/s3list.php
`phan` complains:
https://drone.owncloud.com/owncloud/files_primary_s3/1468/3/3
```
php -d zend.enable_gc=0 vendor-bin/phan/vendor/bin/phan --config-file .phan/config.php --require-config-exists
lib/command/s3list.php:52 PhanTypeMissingReturn Method \OCA\Files_Primary_S3\Command\s3List::execute is declared to return int but has no return value
Makefile:115: recipe for target 'test-php-phan' failed
```
Similar to https://github.com/owncloud/data_exporter/pull/139
I added phpdoc to both `createbucket` and `s3list`. I don't know why `phan` only complained about `s3list`
> Add phpdoc for Symfony Command execute

- .drone.star
We only run acceptance tests with `ceph` currently. Also run the API acceptance tests with `scality` so that we identify anything that has a problem with `scality`.
Note: various core scenarios already have `skipOnStorage:ceph` - we have also tagged those scenarios that need it with `skipOnStorage:scality` (see core PR https://github.com/owncloud/core/pull/37033 )
> [Tests-Only] Run core API tests with scality

- .drone.star
- vendor-bin/behat/composer.json
From core issue https://github.com/owncloud/core/issues/37113
`behat/mink` has to be pinned to `1.7.1` for now.
And while we are here, update the other acceptance test dependencies so they "document" the current minor releases that actually get used.
Note: `symfony/translation` 4.4 requires at least PHP 7.1.3 - that is why I changed `platform` `php`  to `7.1.3`
The 2nd commit makes drone ignore the status of the pipeline step that cleans up the scality bucket. If that fails there is nothing we can do about it anyway, and the tests have already passed.
> Pin behat/mink to 1.7.1 and update other acceptance test dependencies

- Makefile
"backport" of #329 to the release-1.1.2 branch
> [1.1.2] Fix Makefile indent of ifndef

- composer.lock
```
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
- Updating symfony/polyfill-mbstring (v1.14.0 => v1.15.0): Loading from cache
- Updating aws/aws-sdk-php (3.133.22 => 3.134.6): Loading from cache
Generating optimized autoload files
```
> Updating symfony/polyfill-mbstring (v1.14.0 => v1.15.0) and aws-sdk-php

- composer.lock
```
composer update
Updating dependencies (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
- Updating bamarni/composer-bin-plugin (1.4.0 => 1.4.1): Loading from cache
- Updating symfony/polyfill-mbstring (v1.15.0 => v1.17.0): Loading from cache
- Updating aws/aws-sdk-php (3.134.8 => 3.140.1): Loading from cache
Generating optimized autoload files
```
> Bump PHP dependencies as at 20200605

- Makefile
Drone https://drone.owncloud.com/owncloud/files_primary_s3/1828/6/7 failed last night running the PHP unit tests from core.
```
There was 1 error:
1) Tests\Core\Command\Security\RemoveCertificateTest::testRemoveCertificate
file_get_contents(data/certificates/goodCertificate.crt): failed to open stream: No such file or directory
/var/www/owncloud/server/tests/Core/Command/Security/RemoveCertificateTest.php:82
--
There was 1 failure:
1) Tests\Core\Command\Security\ImportCertificateTest::testCommandInput with data set #1 (array('data/certificates/goodCertificate.crt'), array(), 0, '')
Failed asserting that 1 matches expected 0.
/var/www/owncloud/server/tests/Core/Command/Security/ImportCertificateTest.php:69
```
Those tests are new in core. They use certificates that are in the core …
> [Tests-Only] Run core PHP unit tests from core tests dir

- .drone.star
- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiFilesPrimaryS3/restoreVersion.feature
That demonstrate the current "bad behaviour" of issue #387 
The corresponding "good" tests in core are skipped by core PR https://github.com/owncloud/core/pull/37969
When fixing the issue, those core restoreVersion tests need to be unskipped and made to pass. And the "bad behaviour" scenarios in this PR should fail, and can be deleted.
Note: `apiFilesPrimaryS3` already exists in `behat.yml` but it has no scenarios, so it was not being run in CI. This PR adds the suite to drone CI.
> [Tests-Only] Add restoreVersion tests for issue 387

- composer.lock
- lib/streamwrapper.php
- phpstan.neon
- vendor-bin/phan/composer.json
1) Update PHP dependencies
```
Updating dependencies (including require-dev)
Package operations: 0 installs, 5 updates, 0 removals
- Updating symfony/polyfill-mbstring (v1.17.0 => v1.19.0): Loading from cache
- Updating mtdowling/jmespath.php (2.5.0 => 2.6.0): Loading from cache
- Updating guzzlehttp/promises (v1.3.1 => 1.4.0): Loading from cache
- Updating guzzlehttp/psr7 (1.6.1 => 1.7.0): Loading from cache
- Updating aws/aws-sdk-php (3.140.1 => 3.158.14): Loading from cache
Generating optimized autoload files
```
2) Call MimeType::fromFilename instead of deprecated mimetype_from_filename
phan was reporting:
```
lib/streamwrapper.php:169 PhanDeprecatedFunction Call to deprecated function …
```
> Update PHP dependencies

- .drone.star
- composer.json
- composer.lock
- vendor-bin/behat/composer.json
composer v2.0 is now out, and `dg/composer-cleaner` requires updating to the latest version to support that.
Update the PHP  dependencies:
```
Updating dependencies
Lock file operations: 0 installs, 3 updates, 0 removals
- Upgrading aws/aws-sdk-php (3.158.14 => 3.158.18)
- Upgrading dg/composer-cleaner (v2.1 => v2.2)
- Upgrading symfony/polyfill-mbstring (v1.19.0 => v1.20.0)
```
And `behat` dependencies with composer 2.0 only work with PHP 7.4. Set the acceptance test runner to use PHP 7.4.
Part of issue https://github.com/owncloud/core/issues/38067
> Update PHP dependencies for composer 2.0

- .drone.star
Fixes #427 
Adds a set of drone pipelines to run tests against a new scality "ring 8" server that has been provided for us to test against. We are already testing against a scality "ring 7" server, which we continue to do.
PR #433 demonstrates running the full set of core API tests successfully.
This PR just runs the smoke tests, the same as we do for "ring 7". They cover enough of the API usage to verify that a back-end storage is working nicely.
The authentication to the new "ring 8" storage is stored in secrets in the drone server settings https://drone.owncloud.com/owncloud/files_primary_s3/settings
scality_access_key_ring_8
scality_secret_access_key_ring_8
scality_secret_access_key_ring_8_escaped
The value of `scality_secret_access_key_ring_8` had some special characters that needed …
> [tests-only] Add test pipelines for scality ring 8

- .drone.star
- .gitignore
- Makefile
- sonar-project.properties
Part of issue https://github.com/owncloud/QA/issues/649
This PR:
- applies the latest "standard" `.drone.star` code that is used in other oC10 app repos.
- adds SonarCloud analysis to collect PHP unit tests code coverage and do code analysis to SonarCloud https://sonarcloud.io/project/issues?id=owncloud_files_primary_s3
Notes:
- this repo runs the unit tests from `owncloud/core` (it does not have unit tests of its own). With S3 storage "plugged in" and coverage, PHP uses a lot of memory. I adjusted the max memory to 6GB to avoid having the unit tests crash with "out of memory"
- it only collects coverage when run with PHP 7.4. The coverage collection is quite resource-intensive, so I have not collected coverage when the unit tests are run with PHP 7.2 and 7.3. There really should not be …
> [tests-only] Implement SonarCloud analysis

- composer.lock
```
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
- Upgrading aws/aws-sdk-php (3.180.0 => 3.183.9)
- Upgrading symfony/polyfill-mbstring (v1.22.1 => v1.23.0)
```
> Bump symfony/polyfill-ctype v1.23.0 and aws/aws-sdk-php

- tests/acceptance/features/webUIFilesPrimaryS3/webUIFilesPrimaryS3.feature
PR https://github.com/owncloud/core/pull/38795 enhanced the way that the admin storage settings UI works. So the test scenario will no longer work against an old oC10. (There is a new element on the page is only there from oC10.8 onwards). Skip the test scenario on old oC10.
For example https://drone.owncloud.com/owncloud/files_primary_s3/2291/20/13
Note: the scenario here in files_primary_s3 is "a good thing" because it demonstrates the different (better) behavior in files_primary_s3 of core issue https://github.com/owncloud/core/issues/36803
> [tests-only] skip changed webUI AdminStorage Settings tests on old oC10

- .drone.star
Fixes issue #456 
1) Add scality Artesca pipelines to CI 
2) Reduce numberOfParts to avoid drone starlark: maximum file size exceeded - (adding the Artesca pipelines tipped us over the starlark maximum file size, so we have to reduce the number of other pipelines)
We get a CI pass for the 8 new pipelines.
Then:
3) Only run scality artesca pipelines in nightly cron
> [tests-only] [full-ci] Add scality Artesca pipelines to CI

- .drone.star
`csrf` is disabled on the server if the federated server is needed 
- FIxes https://github.com/owncloud/files_primary_s3/issues/466
> [CI] disable crsf on server if federated server is needed

- composer.lock
```
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
- Upgrading aws/aws-sdk-php (3.209.25 => 3.218.3)
- Upgrading symfony/polyfill-mbstring (v1.24.0 => v1.25.0)
```
> Bump symfony polyfill and aws-sdk-php

- .drone.star
This is just for the check if the tests run when notification app is disabled since while auto-loading, as notification app is enabled and the tests uses the core bootstrap for auto-loading  `Class 'OCA\Notifications\Tests\Unit\TestCase'` class is not found.
So trying to run tests without the `notification` app
> [donot-merge]Just check if notification enabled works

- .drone.star
The Artesca Scality S3 test server is unavailable and we are getting no response about it - see issue #564 
So it fails every night in CI.
Drop it from CI. We can easily add it again if the provider gets it going.
> [tests-only] Drop Scality Artesca from CI (issue 564)

- .drone.star
Issue #564 
I updated the access keys in the secrets of https://drone.owncloud.com/owncloud/files_primary_s3/settings/secrets
This PR:
- adjusts the URL for s3.isv.scality.com
- puts back the Artesca nightly CI pipelines - reverts PR #575 
If we merge this PR, then we will find out overnight if it really works.
> [tests-only] Update ring8 and artesca tests

- lib/s3storage.php
- phpstan.neon
Ref https://github.com/owncloud/enterprise/issues/5372
The `CurlMultiHandler` will be used instead of the old StreamHandler in order to support concurrent uploads to the s3 storage. Curl is mandatory, so there is no reason to switch back.
The number of concurrent requests can be adjusted via config.php file:
```
'objectstore' => [
'class' => getenv('OWNCLOUD_OBJECTSTORE_CLASS'),
'arguments' => [
'bucket' => getenv('OWNCLOUD_OBJECTSTORE_BUCKET'),
'autocreate' => getenv('OWNCLOUD_OBJECTSTORE_AUTOCREATE'),
'part_size' => 52428800,
'concurrency' => 4,   // <---------------
'options' => [
'endpoint' => getenv('OWNCLOUD_OBJECTSTORE_ENDPOINT'),
'version' => getenv('OWNCLOUD_OBJECTSTORE_VERSION'),
'region' => getenv('OWNCLOUD_OBJECTSTORE_REGION'),
'use_path_style_endpoint' => …
```
> Allow configurable concurrent uploads

- .drone.star
Bump oc10 server version pins from the drone CI
Fixes: https://github.com/owncloud/files_primary_s3/issues/613
---
Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>
> [tests-only] bump oC10 server pins from the drone CI

- .drone.star
- lib/s3storage.php
- phpstan.neon
Ref: https://github.com/owncloud/enterprise/issues/5372
Recent changes allowed concurrent uploads by using a curlMultiHandler. However, this is causing issues with the downloads because they aren't being streamed properly. Currently, with the curlMultiHandler, we need to download the whole file from S3 before starting sending it to the client. This is causing long delays in the client, which could hit timeouts, specially for big files.
In order to fix this issue, we'll use a different connection in order to handle the downloads. For downloads, we'll use the old streamHandler; for the rest of actions, the new curlMutilHandler. This way, the downloads will be streamed to the client as soon as possible, and we'll still have concurrent uploads.
> Fix stream download release

- CHANGELOG.md
- appinfo/info.xml
- l10n/bg_BG.js
- l10n/bg_BG.json
- sonar-project.properties
> Release 1.4.0

- CHANGELOG.md
There was no 1.3.1 release tagged. Remove it from the changelog links.
Addresses review comment https://github.com/owncloud/files_primary_s3/pull/623/files#r1012265658
Fix a small "typo" in the changelog.
> Adjust changelog release links

- vendor-bin/behat/composer.json
Due to changes in core with this PR https://github.com/owncloud/core/pull/40619. Certain Apps requires to have a package `json-assertion` which was added in core. This PR adds the required package.
https://github.com/owncloud/QA/issues/800
> [tests-only][full-ci]Added `json-assert` library to `files_primary_s3` app

- lib/command/createbucket.php
- lib/command/s3list.php
Symfony 5 will require this, so be prepared.
For Symfony 4 it is optional.
Preparation for https://github.com/owncloud/core/issues/39630
> Always return an int from Symfony Command execute method

- .drone.star
Fixes #663 
It has been decided not to run these "external scality" pipelines in CI. They rely on external test servers that are oftn offline or have certificates expired or...
> [tests-only] [full-ci] Remove external scality test pipelines

- .drone.star
For this repo we have been running the PHP unit tests with multiple core releases.
This PR bumps those core release versions to be up-to-date. It will run with core master, 10.13 and 10.12
PRs related to this in the past are https://github.com/owncloud/activity/pull/1122 https://github.com/owncloud/files_primary_s3/pull/589
> [full-ci] [tests-only] Run unit tests against core master, 10.13 and 10.12

- lib/s3storage.php
- phpstan.neon
Guzzle 5 was dropped with 10.11 - min version of `files_primary_s3` is now 10.12
> chore: drop Guzzle v5

- lib/s3storage.php
https://www.backblaze.com/blog/b2-503-500-server-error/
> feat: BackBlaze B2 upload retry logic

- .drone.star
Fixes #682 
ownCloud core have moved forward since we started running unit tests against 10.12 and 10.3
This PR updates the tests run in CI so that PHP unit tests are run against 10.13.4 (and the daily core master). That is what we really want to know is working.
> test: update core versions for PHP unit tests

- Makefile
We increased the allowed memory from 8G to 12G in PR #492 a few years ago.
Maybe it is not quite enough when the whole set of core unit tests run, and the coverage is being generated.
This might help with issue #682 
(but I also wonder why it needs so much working memory when generating coverage)
> [tests-only] [full-ci] Allow 16G memory for PHP unit tests with coverage

- .drone.star
Fixes #687 
I tried using "latest" but that is the "real release" without test infrastructure built-in.
I tried using "latest-qa" but that does not exist - we don't provide a "latest-qa" that links to "10.15.0-qa".
See commits in #689 where I tries this.
For now, we need to keep putting the actual release version number in here. So I put "10.15.0-qa". We could sort out having a "latest-qa" always available, but I don't think that it is worth trying to sort all that out.
> chore(ci): run unit tests with core 10.15.0
