lib/s3storage.php

Properly stream data from the s3 storage

---

.drone.yml
lib/command/ls.php
lib/s3storage.php
lib/streamwrapper.php

requires https://github.com/owncloud/core/pull/29607

Verisoned buckets

---

lib/s3storage.php

Make part_size configurable

---

.drone.yml

add acceptance tests

---

appinfo/info.xml

This app required php 7.1

---

appinfo/info.xml

Not sure about doc link as docs are still being written.

Initial description, etc.

---

.drone.yml

Second attempt on fixing caching - this time include npm&yarn folders - also use a common `.cache` dir

revalidate caching strategy

---

appinfo/info.xml

Remove "Support" from name in info.xml

---

.drone.yml
appinfo/info.xml
lib/command/createbucket.php
lib/command/ls.php
lib/s3storage.php

- adding s3:createBucket command
- autocreate options has been removed
- list CORS settings in ls command - needed for future releases

Buckets need to be explicitly created - no more auto creation

---

CHANGELOG.md
appinfo/info.xml

Closes https://github.com/owncloud/files_primary_s3/issues/160

Release 1.0.2

---

Makefile

Use GNU format for tar

---

CHANGELOG.md
Makefile
appinfo/info.xml

Closes https://github.com/owncloud/files_primary_s3/issues/175

Release 1.0.3

---

.drone.yml

analogue to to https://github.com/owncloud/user_management/pull/169 disable the integrity check to make the webUI not report failures

disable integrity check for tests

---

.drone.yml

the core acceptance tests are growing, so better to split them here in more parts so that CI gets faster

Split core tests

---

composer.lock

Note: no changes needed for PHPUnit 5 to 6

Updating bamarni/composer-bin-plugin (v1.2.0 => v1.3.0)

---

lib/s3storage.php

Reverts owncloud/files_primary_s3#205

Revert "Always provide return status for functions"

---

lib/s3storage.php

Throw exception when the file is not written to
the object storage.
Signed-off-by: Sujith H <sharidasan@owncloud.com>

Throw exception when the file is not written to the storage

---

CHANGELOG.md
appinfo/info.xml

1.0.4 release date

---

CHANGELOG.md

Add new unreleased section after 1.0.4

---

.drone.starlark
.drone.yml
.gitignore

If a nightly build has failure, then nothing is being reported in rocketchat, because the pipelines stop once there is a failure. So the notify pipeline is never executed.
This:
- adjusts the drone config so that the notify pipeline will execute on both success and failure.
- implements the latest "standard" app drone starlark code (copied from activity app)
- adds "standard" items to `.gitignore`

Update drone starlark with latest code 20191011

---

.drone.starlark
.drone.yml
lib/command/createbucket.php
lib/command/s3list.php
lib/s3storage.php
lib/streamwrapper.php

Fixes issue #208 
See my comments on lines of code that I needed to touch.

Enable phan and phpstan

---

.drone.starlark
.drone.yml
vendor-bin/behat/composer.json

Similar to https://github.com/owncloud/configreport/pull/121
Note: this app has no phpunit tests to fix

Allow behat to locally find guzzle and phpunit

---

vendor-bin/owncloud-codestyle/composer.json

like done in core https://github.com/owncloud/core/pull/36580
(drone starlark is already up-to-date)
Note: there were no changes to PHP code needed for this app to pass code-style 2.0.0

Implement coding-standard 2.0.0

---

lib/s3storage.php

Format message thrown by AWS exception. There
are details in the message which can cause security
breach.
Signed-off-by: Sujith H <sharidasan@owncloud.com>

Format message thrown by AWS exception

---

CHANGELOG.md
appinfo/info.xml

Closes https://github.com/owncloud/files_primary_s3/issues/291

Merge back Release 1.1.0

---

lib/s3storage.php

Catch MultipartUploadException when uploading large
files.
Signed-off-by: Sujith H <sharidasan@owncloud.com>

Catch Mulipart execption when uploading large files

---

CHANGELOG.md
appinfo/info.xml

Merge back Release 1.1.1

---

.drone.star
Makefile
tests/delete_all_object_versions.sh

run smoke API tests on test-infrastructure provided by scality
fixes https://github.com/owncloud/enterprise/issues/3868

[Tests-only] run smoke tests on s3.isv.scality.com

---

.drone.star

That was done in activity app PR https://github.com/owncloud/activity/pull/838
So that we have consistent starlark code in this app.

[Tests-Only] Apply latest .drone.star code

---

Makefile

Fixes issue #328 
The indent happened in PR #325

Fix Makefile indent of ifndef

---

lib/streamwrapper.php
phpstan.neon
vendor-bin/phpstan/composer.json

Related - owncloud/QA#642
Update phpstan to 0.12

[Tests-Only] Update phpstan to latest version

---

.drone.star
Makefile
composer.json
composer.lock
l10n/he.js
l10n/he.json
l10n/ru.js
l10n/ru.json
lib/streamwrapper.php
phpstan.neon
vendor-bin/phpstan/composer.json

So that translations end up in the released app.

[release-1.1.2] Add l10n to dist/appstore build

---

lib/streamwrapper.php
vendor-bin/phan/composer.json

Part of https://github.com/owncloud/QA/issues/643

[Tests-Only] Bump phan 2.7

---

Makefile
tests/acceptance/config/behat.yml
tests/acceptance/features/apiFilesPrimaryS3/apiFilesPrimaryS3.feature
tests/acceptance/features/bootstrap/FilesPrimaryS3Context.php
tests/acceptance/features/bootstrap/bootstrap.php

setup acceptance tests infrastructure.
Fixes #359

[Tests-Only] setup acceptance tests infrastructure

---

.drone.star
Makefile
tests/acceptance/config/behat.yml
tests/acceptance/features/webUIFilesPrimaryS3/webUIFilesPrimaryS3.feature

This PR adds an acceptance  test for sharing of local storage.
- Fixes https://github.com/owncloud/files_primary_s3/issues/351

[Tests-Only] Run acceptance tests

---

.drone.star

These changes had been made recently in the activity app, but not applied here in files_primary_s3.
That caused me a bit of confusion - working in both apps!
Apply the latest `.drone.star` changes here.

[tests-only] Apply latest drone starlark code

---

.drone.star

Same as https://github.com/owncloud/activity/pull/991 and https://github.com/owncloud/activity/pull/992
This will get `.drone.star` up-to-date.

[tests-only] Replace tabs with spaces in .drone.star and add check-starlark pipeline

---

.drone.star
Makefile
appinfo/info.xml
composer.json
composer.lock

Part of issue https://github.com/owncloud/core/issues/39134
and https://github.com/owncloud/QA/issues/687
and for the latest `.drone.star` code from activity app.

[full-ci] Update .drone.star for 'drop PHP 7.2 support'

---

.drone.star

Drop duplicate PHP 7.4 pipelines

---

.drone.star

[tests-only] [full-ci] Support download tests in .drone.star

---

.drone.star
lib/s3storage.php
lib/streamwrapper.php
vendor-bin/phan/composer.json

1) Bump PHP phan to major version 5
Part of https://github.com/owncloud/QA/issues/696

Bump PHP phan to major version 5

---

tests/acceptance/features/bootstrap/FilesPrimaryS3Context.php
tests/acceptance/features/bootstrap/bootstrap.php

Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script

[Tests-Only] enforce strict type checking in acceptace tests code

---

CHANGELOG.md
Makefile
appinfo/info.xml
js/settings.js
sonar-project.properties

Release 1.1.3

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

merge back after successful release #524

Bump version, update changelog

---

.drone.star
appinfo/info.xml
composer.json
composer.lock
lib/s3storage.php

https://github.com/owncloud/core/pull/39368 bumps Guzzle to v7 in core. These changes are necessary to make it work with a s3 primary storage.

[full-ci] Add compatibility with Guzzle 7

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

the release branch is still named release-2.0.0, but we renamed the release to 1.3.0
Closes #577

Release 1.3.0 done

---

phpstan.neon

specify which file the error happens in - that makes it a bit easier to understand

[tests-only] [full-ci] Improve phpstan.neon ignoreErrors

---

.drone.star
composer.json
composer.lock
lib/Panels/Admin.php
lib/command/createbucket.php
lib/command/s3list.php
lib/s3storage.php
phpstan.neon
vendor-bin/behat/composer.json
vendor-bin/owncloud-codestyle/composer.json
vendor-bin/phpstan/composer.json

- update `.drone.star` code from activity app
- update tool dependencies
- update to coding-style 4.1
The following dependencies updated:
```
Lock file operations: 0 installs, 3 updates, 0 removals
- Upgrading aws/aws-crt-php (v1.0.2 => v1.2.1)
- Upgrading guzzlehttp/promises (1.5.1 => 1.5.3)
- Upgrading symfony/polyfill-mbstring (v1.26.0 => v1.27.0)
```

[tests-only] [full-ci] Update tool dependencies and drone CI code
